### ISSUE TITLE
COFEEDX is not loading

### ISSUE THREAD

**Issue by ustroetz** [tmcw/coffeedex#15]
After the OSM login the application just stops at the loading screen:
Tested on Safari 8.0 and Chrome 39.0.2171.71 (64-bit)
![screen shot 2014-11-30 at 19 23 57](https://cloud.githubusercontent.com/assets/4493762/5240317/848c4ef8-78c6-11e4-9477-55d6163a3d7e.png)

**Comment by tmcw** [comment]
You might not have any coffee shops near you. Ref #11

**Comment by ustroetz** [comment]
Yeah that is the case.
