### ISSUE TITLE
Spinoff: wifidex

### ISSUE THREAD

**Issue by tmcw** [tmcw/coffeedex#19]
This is basically a zany mixture of coffeedex with @maxogden's ssid-checkin.

UX:

You install the thing as a mac osx app (atom-editor wrapper or similar), it gives you the same 'optionally check in when you connect to an ssid you know aligns with a foursquare venue' functionality of ssid-checkin.

Differences being:
- the data is in openstreetmap
- optionally: the app tries to give you more value than a checkin: closing times, tips, something else

The boring pedantics:
- [ssid key is kosher](http://wiki.openstreetmap.org/wiki/Key:internet_access) and [pretty mildly used](http://taginfo.openstreetmap.org/keys/internet_access%3Assid)
- [foursquare key is possible](http://taginfo.openstreetmap.org/search?q=foursquare) and [proposed](http://wiki.openstreetmap.org/wiki/Talk:Proposed_features/link). 

Cool thing about where this app would live is that it would make contributing these two tags dead-simple.

**Comment by CloCkWeRX** [comment]
Its a pity this one didn't go too far - foursquare's ability to prompt you for useful questions about a place is very handy; and something that I miss from other editors like vespucci when out and about.

**Comment by tmcw** [comment]
Would welcome a contribution in this direction - I unfortunately don't have infinite time, and this isn't the highest priority.
