### ISSUE TITLE
Can't authenticate OSM

### ISSUE THREAD

**Issue by jwass** [tmcw/coffeedex#23]
Clicking the Login button on coffeedex gives this error in the console, and nothing happens:

```
 XMLHttpRequest cannot load http://www.openstreetmap.org/oauth/request_token. The request was redirected to 'https://www.openstreetmap.org/oauth/request_token', which is disallowed for cross-origin requests that require preflight.
```

on Chrome 39.0.2171.71 (64-bit). Similar behavior on Chrome on iOS 8.1.1. Safari has issues too, guessing same thing..?

**Comment by tmcw** [comment]
Looks like OSM may have turned off CORS on their OAuth implementation.

**Comment by jwass** [comment]
This has been fixed for some time now.
